# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pljournal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pljournal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpljournal.proto\x12\x03plj\"\xb0\x01\n\x12JournalEntryHeader\x12\x12\n\nentry_type\x18\x01 \x01(\x04\x12\x14\n\x0cpayload_uuid\x18\x02 \x01(\x0c\x12\x12\n\npayload_id\x18\x03 \x01(\t\x12\x17\n\x0fpayload_version\x18\x04 \x01(\x04\x12\x16\n\x0epayload_length\x18\x05 \x01(\x04\x12\x13\n\x0bpayload_crc\x18\x06 \x01(\r\x12\x16\n\x0enil_properties\x18\x07 \x03(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pljournal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOURNALENTRYHEADER']._serialized_start=25
  _globals['_JOURNALENTRYHEADER']._serialized_end=201
# @@protoc_insertion_point(module_scope)
